# Generated by Django 4.1.5 on 2023-01-12 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='property_manager',
            new_name='p_manager',
        ),
    ]
