# Generated by Django 4.1.5 on 2023-01-12 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_property_manager_client_p_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='name',
        ),
    ]
